import random
class Dice(object):
    def __init__(self, lower, upper):
        self.lower = lower
        self.upper = upper

    def roll(self):
        return random.randint(self.lower, self.upper)

d = Dice(1, 6)
print(d.roll())
print(d.roll())
print(d.roll())
print(d.roll())
print(d.roll())
print(d.roll())
print(d.roll())
print(d.roll())
print(d.roll())
print(d.roll())
print(d.roll())
print(d.roll())

print("##################################################################################")
d2 = Dice(2,12)
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print(d2.roll())
print("##################################################################################")

d3 = Dice(1,4)
print(d3.roll())
print(d3.roll())
print(d3.roll())
print(d3.roll())
print(d3.roll())
print(d3.roll())
print(d3.roll())
print(d3.roll())
print(d3.roll())
print(d3.roll())
